### ISSUE TITLE
Using .end() without the flush parameter is deprecated and throws from v.3.0.0 on

### ISSUE THREAD

**Issue by TiTi** [jeremyfa/node-redis-dump#12]
I'm using the `dump()` function in a nodejs script.
I got this warning on stderr:

> node_redis: Using .end() without the flush parameter is deprecated and throws from v.3.0.0 on.
> Please check the doku (https://github.com/NodeRedis/node_redis) and explictly use flush.

Also it seems each call to dump() does not close the connection.
I'm therefore ending up with a lot of connections opened after many calls to  `dump()` :-(
To the point I'm exhausting redis connections: 

> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: Redis connection to 171.40.11.07:6379 failed - connect ETIMEDOUT 171.40.11.07:6379
>     at Object.exports._errnoException (util.js:837:11)
>     at exports._exceptionWithHostPort (util.js:860:20)
>     at TCPConnectWrap.afterConnect [as oncomplete](net.js:1060:14)

(this depends on your redis and linux tcp settings)

**Comment by jeremyfa** [comment]
Indeed, these need to be fixed. Thanks for reporting!

**Comment by rodrigoaguilera** [comment]
PR sent
