### ISSUE TITLE
SSl Suport

### ISSUE THREAD

**Issue by Skylertodd** [jeremyfa/node-redis-dump#18]
While trying to dump a database with require SSL connect true, in azure, I am stopped by
 
```
events.js:183
      throw er; // Unhandled 'error' event
      ^
AbortError: Ready check failed: Redis connection lost and command aborted. It might have been processed.
    
at RedisClient.flush_and_error (...\npm\node_modules\redis-dump\node_modules\redis\index.js:362:23)
    
at RedisClient.connection_gone (...\npm\node_modules\redis-dump\node_modules\redis\index.js:664:14)
    
at Socket.<anonymous> (...\npm\node_modules\redis-dump\node_modules\redis\index.js:293:14)
    
at Object.onceWrapper (events.js:313:30)
    
at emitNone (events.js:111:20)
    
at Socket.emit (events.js:208:7)
    
at endReadableNT (_stream_readable.js:1055:12)
    
at _combinedTickCallback (internal/process/next_tick.js:138:11)
    
at process._tickCallback (internal/process/next_tick.js:180:9)
```

I am assuming this issue is caused by SSL but unsure.

**Comment by stefanotauriello** [comment]
Same problem.... 😩

**Comment by arcavid** [comment]
No one needs this anymore?
