### ISSUE TITLE
TypeError: Cannot set property 'ttl' of undefined

### ISSUE THREAD

**Issue by dionjwa** [jeremyfa/node-redis-dump#19]
I sporadically see this error when dumping json from redis. I cannot reproduce the exact conditions, but the check to avoid the stack trace is looks straightforward.

```
TypeError: Cannot set property 'ttl' of undefined
    at /app/node_modules/redis-dump/bin/dump.js:309:37
    at fn (/app/node_modules/async/lib/async.js:746:34)
    at /app/node_modules/async/lib/async.js:1213:16
    at /app/node_modules/async/lib/async.js:166:37
    at /app/node_modules/async/lib/async.js:706:43
    at /app/node_modules/async/lib/async.js:167:37
    at Multi.callback (/app/node_modules/async/lib/async.js:1209:30)
    at multi_callback (/app/node_modules/redis/lib/multi.js:89:14)
    at Command.callback (/app/node_modules/redis/lib/multi.js:116:9)
    at normal_reply (/app/node_modules/redis/index.js:726:21)
    at RedisClient.return_reply (/app/node_modules/redis/index.js:824:9)
    at JavascriptRedisParser.returnReply (/app/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/app/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/app/node_modules/redis/index.js:274:27)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
```

Pull request attached.

**Comment by JasonLaw1994** [comment]
Encounter the same problem, why hasn't the pull request been merged? Any update?
